[tox]
env_list = py314
isolated_build = true

[testenv:py314]
description = Run the Python unit tests.
extras = test
setenv =
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY = 1
commands =
    pytest --cov=fincore --cov-report=term-missing --cov-report=xml {posargs:tests}

[testenv:.pkg]
setenv =
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY = 1
